# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ".*.patch$ ^Echo/ ^model/"
      - id: check-json
        exlude: "^Echo/ ^model/"
      - id: check-yaml
        exlude: "^Echo/ ^model/"
      - id: debug-statements
        exlude: "^Echo/ ^model/"
      - id: check-merge-conflict
        exlude: "^Echo/ ^model/"
      - id: end-of-file-fixer
        exlude: "^Echo/ ^model/"
      - id: pretty-format-json
        exlude: "^Echo/ ^model/"
        args:
          - "--autofix"
          - "--indent=4"
          - "--no-sort-keys"
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        exlude: "^Echo/ ^model/"
        args:
        - "--line-length=127"
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        exlude: "^Echo/ ^model/"
