AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  echo

  Sample SAM Template for echo

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 256

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
  
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: layers
      CompatibleRuntimes:
        - python3.11
  
  LibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: LibLayer
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11

  CreatePostFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: CreatePostFunction/
      Handler: create_post.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Layers:
      - !Ref MyLayer
      - !Ref LibLayer
      Environment:
        Variables:
          MONGO_DB_ID: !Ref MongoDBId
          MONGO_DB_PWD: !Ref MongoDBPwd
      Events:
        Forum:
          Type: Api
          Properties:
            Path: /create-post
            Method: post
  CreateProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: CreateProfileFunction/
      Handler: create_profile.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Layers:
      - !Ref MyLayer
      - !Ref LibLayer
      Environment:
        Variables:
          MONGO_DB_ID: !Ref MongoDBId
          MONGO_DB_PWD: !Ref MongoDBPwd
      Events:
        Forum:
          Type: Api
          Properties:
            Path: /create-profile
            Method: post

Parameters:
  MongoDBId:
    Type: String
  MongoDBPwd:
    Type String

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MyLayer:
    Description: "Local Packages Layer"
    Value: !Ref MyLayer
    Export:
      Name: !Sub '${AWS::StackName}-MyLayerArn'
  
  LibLayer:
    Description: "Layer containing following libraries: pymongo"
    Value: !Ref LibLayer
    Export:
      Name: !Sub '${AWS::StackName}-LibLayer'
 
  CreatePostApi:
    Description: API Gateway endpoint URL for Prod stage for Create Post function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create-post/"
  CreatePostFunction:
    Description: Create Post Lambda Function ARN
    Value: !GetAtt CreatePostFunction.Arn
  CreatePostFunctionIamRole:
    Description: Implicit IAM Role created for Create Post function
    Value: !GetAtt CreatePostFunctionRole.Arn

  CreateProfileApi:
    Description: API Gateway endpoint URL for Prod stage for Create Profile function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create-profile/"
  CreateProfileFunction:
    Description: Create Profile Lambda Function ARN
    Value: !GetAtt CreateProfileFunction.Arn
  CreateProfileFunctionIamRole:
    Description: Implicit IAM Role created for Create Profile function
    Value: !GetAtt CreateProfileFunctionRole.Arn
