AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  echo

  Sample SAM Template for echo

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
   
  ForumFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ForumFunction/
      Handler: forum.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        Forum:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /forum
            Method: get

  PostCreateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: PostCreateFunction/
      Handler: post_create.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        Forum:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /post-create
            Method: post

  PostReadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: PostReadFunction/
      Handler: post_read.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        Forum:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /post-read
            Method: get

  ProfileCreateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ProfileCreateFunction/
      Handler: profile_create.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        Forum:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /profile-create
            Method: post

  ProfileReadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ProfileReadFunction/
      Handler: profile_read.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        Forum:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /profile-read
            Method: get

  ReactFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ReactFunction/
      Handler: react.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        Forum:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /react
            Method: post

  UndoReactFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: UndoReactFunction/
      Handler: undo_react.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        Forum:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /undo-react
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ForumApi:
    Description: API Gateway endpoint URL for Prod stage for Forum function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/forum/"
  ForumFunction:
    Description: Forum Lambda Function ARN
    Value: !GetAtt ForumFunction.Arn
  ForumFunctionIamRole:
    Description: Implicit IAM Role created for Forum function
    Value: !GetAtt ForumFunctionRole.Arn
 
  PostCreateApi:
    Description: API Gateway endpoint URL for Prod stage for Post Create function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/post-create/"
  PostCreateFunction:
    Description: Post Create Lambda Function ARN
    Value: !GetAtt PostCreateFunction.Arn
  CreateFunctionIamRole:
    Description: Implicit IAM Role created for Post Create function
    Value: !GetAtt PostCreateFunctionRole.Arn

  PostReadApi:
    Description: API Gateway endpoint URL for Prod stage for Post Read function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/post-read/"
  PostReadFunction:
    Description: Post Read Lambda Function ARN
    Value: !GetAtt PostReadFunction.Arn
  PostReadFunctionIamRole:
    Description: Implicit IAM Role created for Post Read function
    Value: !GetAtt PostReadFunctionRole.Arn

  ProfileCreateApi:
    Description: API Gateway endpoint URL for Prod stage for Profile Create Read function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/profile-create/"
  ProfileCreateFunction:
    Description: Profile Create Lambda Function ARN
    Value: !GetAtt ProfileCreateFunction.Arn
  ProfileCreateFunctionIamRole:
    Description: Implicit IAM Role created for Profile Create function
    Value: !GetAtt ProfileCreateFunctionRole.Arn

  ProfileReadApi:
    Description: API Gateway endpoint URL for Prod stage for Profile Read function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/profile-read/"
  ProfileReadFunction:
    Description: Profile Read Lambda Function ARN
    Value: !GetAtt ProfileReadFunction.Arn
  ProfileReadFunctionIamRole:
    Description: Implicit IAM Role created for Profile Read function
    Value: !GetAtt ProfileReadFunctionRole.Arn

  ReactApi:
    Description: API Gateway endpoint URL for Prod stage for React function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/react/"
  ReactFunction:
    Description: React Lambda Function ARN
    Value: !GetAtt ReactFunction.Arn
  ReactFunctionIamRole:
    Description: Implicit IAM Role created for React function
    Value: !GetAtt ReactFunctionRole.Arn

  UndoReactApi:
    Description: API Gateway endpoint URL for Prod stage for Undo React function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/undo-react/"
  UndoReactFunction:
    Description: Undo React Lambda Function ARN
    Value: !GetAtt UndoReactFunction.Arn
  UndoReactFunctionIamRole:
    Description: Implicit IAM Role created for Undo React function
    Value: !GetAtt UndoReactFunctionRole.Arn
