AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  echo

  Sample SAM Template for echo

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

    Tracing: Active
  Api:
    TracingEnabled: true
Resources:
   
  ForumFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ForumFunction/
      Handler: forum.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        Forum:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /forum
            Method: get

  PostFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: PostFunction/
      Handler: post.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        Forum:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /post
            Method: get

  ProfileFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ProfileFunction/
      Handler: profile.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        Forum:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /profile
            Method: get

  ReactFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ReactFunction/
      Handler: react.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        Forum:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /react
            Method: post

  SaveYapFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: SaveYapFunction/
      Handler: save_yap.lambda_handler
      Runtime: python3.11
      Architectures:
      - x86_64
      Events:
        Forum:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /save-yap
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ForumApi:
    Description: API Gateway endpoint URL for Prod stage for Forum function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/forum/"
  ForumFunction:
    Description: Forum Lambda Function ARN
    Value: !GetAtt ForumFunction.Arn
  ForumFunctionIamRole:
    Description: Implicit IAM Role created for Forum function
    Value: !GetAtt ForumFunctionRole.Arn

  PostApi:
    Description: API Gateway endpoint URL for Prod stage for Post function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/post/"
  PostFunction:
    Description: Post Lambda Function ARN
    Value: !GetAtt PostFunction.Arn
  PostFunctionIamRole:
    Description: Implicit IAM Role created for Post function
    Value: !GetAtt PostFunctionRole.Arn

  ProfileApi:
    Description: API Gateway endpoint URL for Prod stage for Profile function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/profile/"
  ProfileFunction:
    Description: Profile Lambda Function ARN
    Value: !GetAtt ProfileFunction.Arn
  ProfileFunctionIamRole:
    Description: Implicit IAM Role created for Profile function
    Value: !GetAtt ProfileFunctionRole.Arn

  React Api:
    Description: API Gateway endpoint URL for Prod stage for React function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/react/"
  ReactFunction:
    Description: React Lambda Function ARN
    Value: !GetAtt ReactFunction.Arn
  ReactFunctionIamRole:
    Description: Implicit IAM Role created for React function
    Value: !GetAtt ReactFunctionRole.Arn

  SaveYapApi:
    Description: API Gateway endpoint URL for Prod stage for Save Yap function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/save-yap/"
  SaveYapFunction:
    Description: Save Yap Lambda Function ARN
    Value: !GetAtt SaveYapFunction.Arn
  SaveYapFunctionIamRole:
    Description: Implicit IAM Role created for SaveYap function
    Value: !GetAtt SaveYapFunctionRole.Arn
